[user]
    name = George Palmer-Bryant
	email = georgepalmerbryant@gmail.com

[core]
    # Use the personal GitHub SSH key for repos in this directory, ignoring any other keys the SSH agent may have loaded
    sshCommand = ssh -i ~/.ssh/id_ed25519_personal_github -o IdentitiesOnly=yes
