#!/bin/zsh

function refresh {
    local target_branch
    if [ "$1" != "" ]
    then
        target_branch="$1"
    else
        target_branch="staging"
    fi
    git fetch
    git switch $target_branch && git pull && git switch -
}

function mkcd() {
    mkdir -p "$@" && cd "$_";
}
